version: '3.8'

services:
    api:
      build: .
      ports:
        - "8081:8080"
      environment:
        DB_HOST: database
      depends_on:
        - database
      restart: on-failure
    database:
      container_name: "database"
      image: postgres:alpine
      environment:
        POSTGRES_DB: "app_db"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
      ports:
        - "5432:5432"
      restart: always