version: '3.8'
services:
  api:
    build:
      context: .
    container_name: api
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - postgres
      - redis
      - seaweedfs
      - greenmail
    networks:
      - backend_network
    env_file:
      - .dev.env
  front-end:
    build:
      context: ./photo-sharing-application-front-end/
    container_name: front-end
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      - api
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    networks:
      - backend_network
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure
    command: /bin/sh -c "redis-server /usr/local/etc/redis.conf"
    volumes:
      - ./redis:/usr/local/etc
      - redis:/data
    networks:
      - backend_network
  seaweedfs:
    image: chrislusf/seaweedfs
    container_name: seaweedfs
    ports:
      - "8333:8333"
    restart: on-failure
    command:
      - 'server -s3 -s3.config=/var/lib/seaweedfs/config.json'
    volumes:
      - ./seaweedfs:/var/lib/seaweedfs
      - seaweedfs:/data
      - seaweedfs:/tmp
    networks:
      - backend_network
  greenmail:
    image: greenmail/standalone:latest
    container_name: greenmail
    ports:
      - "3025:3025" # SMTP
      - "8082:8080" # API
      - "3110:3110" # POP3
    restart: on-failure
    environment:
      - JAVA_OPTS=-Dgreenmail.verbose -Dgreenmail.users=user:password -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.startup.timeout=3500
    networks:
      - backend_network
volumes:
  redis:
  seaweedfs:
  postgres:
  pgadmin:
networks:
  backend_network: