version: '3.8'

services:
  api:
    build: .
    ports:
      - "8081:8080"
    environment:
      ACTIVE_PROFILE: dev
      DB_HOST: postgres
    depends_on:
      - postgres
      - redis
    restart: on-failure
  postgres:
    image: postgres:alpine
    restart: on-failure
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    links:
      - postgres
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
  seaweedfs:
    image: chrislusf/seaweedfs
    restart: on-failure
    volumes:
      - seaweedfs:/var/lib/seaweedfs/data
    ports:
      - "8333:8333"
    command:
    - "server -s3"
#    When this container starts go to the terminal
#    and type  echo 's3.configure -access_key any -secret_key any -user admin -actions Admin -apply' | weed shell
  greenmail:
    image: greenmail/standalone:latest
    restart: on-failure
    volumes:
      - greenmail:/var/lib/greenmail/data
    environment:
      - JAVA_OPTS=-Dgreenmail.verbose -Dgreenmail.users=user:pwd
    ports:
      - 3025:3025 # SMTP
      - 8082:8080 # API
      - 3110:3110 # POP3
volumes:
  seaweedfs:
  database:
  redis:
  greenmail: