version: '3.8'

services:
  api:
    build: .
    ports:
      - "8081:8080"
    environment:
      ACTIVE_PROFILE: "dev"
      DB_HOST: database
    depends_on:
      - database
      - redis
    restart: on-failure
  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "app_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    restart: on-failure
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: on-failure

  s3:
    image: chrislusf/seaweedfs
    volumes:
      - seaweedfs:/seaweedfs
    ports:
      - "8333:8333"
    command:
    - "server -s3"
#    When this container starts go to the terminal
#    and type  echo 's3.configure -access_key any -secret_key any -user admin -actions Admin -apply' | weed shell

volumes:
  seaweedfs:
