spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  session:
    store-type: redis
    timeout: 1h
