spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  data:
    redis:
      password: ${REDIS_PASSWORD}
  cache:
    cache-names: images
    redis:
      time-to-live: 10m
      key-prefix: "spring:cache:"
      cache-null-values: false
    type: redis
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  session:
    timeout: 1h
    store-type: redis
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  encryption:
    salt: ${ENCRYPTION_PASSWORD}
    password: ${ENCRYPTION_SALT}
server:
  port: ${SERVER_PORT:8080}