spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/app_db
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  redis:
    namespace: spring:session
    host: localhost
    port: 6379
  session:
    timeout: 1h
    store-type: redis
s3:
  url: "http://localhost:8333"
  bucket_name: "accounts_data"
  access_key: "any"
  secret_key: "any"

