spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
