spring:
  mail:
    password: pwd
    username: user
    host: 127.0.0.1
    port: 3025
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/app_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  redis:
    namespace: spring:session
    host: localhost
    port: 6379
  session:
    timeout: 1h
    store-type: redis
s3:
  url: "http://localhost:8333"
  bucket_name: "accounts_data"
  access_key: "any"
  secret_key: "any"
