name: Java CI with Maven

on: pull_request

jobs:

  build:
    name: "Build the project"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Build a package with Maven
        run: mvn clean package -B --file pom.xml -DskipTests

  test:
    name: "Run the tests"
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile tests
        run: mvn clean test-compile

      - name: Run unit tests
        run: mvn surefire:test

      - name: Run integrations tests
        run: mvn failsafe:integration-test



